
// ======================
// BcftoolsConcat
// ======================
/*
 * Concatenates VCF files, adds an explicit INFO/TYPE tag for SNP/INDEL,
 * and produces both compressed and uncompressed output VCFs.
 *
 * Args:
 *   vcfs (List): List of compressed VCF file paths (e.g., SNP and INDEL VCFs).
 *   read_alias (String): Prefix for the output files.
 *
 * Output:
 *   ${read_alias}.vcf.gz        - merged VCF, compressed
 *   ${read_alias}_final.vcf.gz  - merged VCF with TYPE tag, compressed
 *   ${read_alias}_final.vcf     - merged VCF with TYPE tag, uncompressed
 */
def BcftoolsConcat(vcfs, read_alias) {
    """
    bcftools concat -a ${vcfs.join(' ')} -Oz -o ${read_alias}.vcf.gz
    bcftools +fill-tags ${read_alias}.vcf.gz -- -t TYPE -o ${read_alias}_final.vcf.gz -Oz
    gunzip -c ${read_alias}_final.vcf.gz > ${read_alias}_final.vcf
    """.stripIndent().trim()
}

// ======================
// TabixVCF
// ======================
/*
 * Indexes a bgzipped VCF file using tabix, enabling fast random access
 * and compatibility with tools such as bcftools, IGV, and others.
 *
 * Args:
 *   vcf (String): Path to the bgzipped VCF file (should end with .vcf.gz).
 *
 * Output:
 *   ${vcf}.tbi - Tabix index file created alongside the input VCF.
 *
 * Assumptions:
 *   - Input VCF is bgzipped (.vcf.gz).
 *   - tabix is available in the PATH.
 */
def TabixVCF(
    vcf
) {
    return "tabix -p vcf ${vcf}"
}

// ======================
// VarscanMpileup2Indel
// ======================
/*
 * Calls INDEL variants from a pileup file using VarScan2 and outputs
 * a bgzipped VCF file suitable for downstream analysis.
 *
 * Args:
 *   mpileup (String): Path to the input pileup file (SAMtools pileup format).
 *   output_tag (String): Prefix or tag for the output file.
 *
 * Output:
 *   ${output_tag}.vcf.gz - Compressed VCF file containing INDEL variant calls.
 *
 * Assumptions:
 *   - VarScan2 and bgzip are available in the PATH.
 *   - Input pileup is correctly formatted and compatible with VarScan2.
 */
def VarscanMpileup2Indel(
    mpileup,
    output_tag
) {
    return """
    varscan mpileup2indel "${mpileup}" \
        --min-var-freq 0.001 \
        --min-reads2 2 \
        --min-coverage 10 \
        --p-value 0.01 \
        --output-vcf 1 | bgzip -c > "${output_tag}.vcf.gz"
    """.stripIndent().trim()
}

// ======================
// VarscanMpileup2Snp
// ======================
/*
 * Calls SNP variants from a pileup file using VarScan2 and outputs
 * a bgzipped VCF file suitable for downstream analysis.
 *
 * Args:
 *   mpileup (String): Path to the input pileup file (SAMtools pileup format).
 *   output_tag (String): Prefix or tag for the output file.
 *
 * Output:
 *   ${output_tag}.vcf.gz - Compressed VCF file containing SNP variant calls.
 *
 * Assumptions:
 *   - VarScan2 and bgzip are available in the PATH.
 *   - Input pileup is correctly formatted and compatible with VarScan2.
 */
def VarscanMpileup2Snp(
    mpileup,
    output_tag
) {
    return """
    varscan mpileup2snp "${mpileup}" \
        --min-var-freq 0.001 \
        --min-reads2 2 \
        --min-coverage 10 \
        --p-value 0.01 \
        --output-vcf 1 | bgzip -c > "${output_tag}.vcf.gz"
    """.stripIndent().trim()
}

// ======================
// SamtoolsMpileup
// ======================
/*
 * Generates a pileup file from aligned reads using samtools mpileup,
 * suitable for variant calling tools such as VarScan2.
 *
 * Args:
 *   reference (String): Path to the reference FASTA file.
 *   reads (String): Path to the input BAM or SAM file.
 *   min_quality (Integer): Minimum base quality for bases to be included.
 *   max_depth (Integer, optional): Maximum read depth per position (default: 30000).
 *   read_alias (String): Prefix or alias for the output pileup file.
 *
 * Output:
 *   ${read_alias}_samtools.pileup - Pileup file generated by samtools.
 *
 * Assumptions:
 *   - Samtools is available in the PATH.
 *   - Input BAM/SAM file is sorted and indexed if required.
 *   - Reference FASTA is indexed (.fai).
 */
def SamtoolsMpileup(
    reference,
    reads,
    min_quality,
    max_depth=30000,
    read_alias
) {
    return """
    samtools mpileup -f "${reference}" \
        -B \
        -Q "${min_quality}" \
        -d "${max_depth}" \
        "${reads}" > "${read_alias}_samtools.pileup"
    """.stripIndent().trim()
}

// ======================
// RunIndexing
// ======================
/*
 * Indexes a BAM file using samtools, creating an index file (.bai) for rapid random access.
 *
 * Args:
 *   reads (String): Path to the BAM file to be indexed.
 *
 * Output:
 *   ${reads}.bai - Index file created alongside the BAM file.
 *
 * Assumptions:
 *   - Samtools is available in the PATH.
 *   - Input file is a valid and sorted BAM file.
 */
def RunIndexing(reads){
    return "samtools index ${reads}"
}

// ======================
// DetermineCoverage
// ======================
/*
 * Computes per-base coverage depth from a BAM file using samtools depth,
 * and outputs a CSV-formatted report of coverage by position.
 *
 * Args:
 *   reads (String): Path to the BAM file for which coverage will be calculated.
 *   read_alias (String): Prefix or alias for the output CSV report.
 *
 * Output:
 *   ${read_alias}_coverage_report.csv - CSV file with columns: CHROM, POS, DEPTH.
 *
 * Assumptions:
 *   - Samtools and awk are available in the PATH.
 *   - Input BAM file is valid, sorted, and indexed if required.
 */
def DetermineCoverage(reads, read_alias) {
    return "samtools depth -a ${reads} | awk 'BEGIN{OFS=\",\"} {print \$1, \$2, \$3}' > ${read_alias}_coverage_report.csv"
}

// ======================
// Bam2FqQualLenFilter
// ======================
/*
 * Converts a BAM file to FASTQ format and filters reads by quality and length using chopper.
 *
 * Args:
 *   reads (String): Path to the input BAM file.
 *   output (String): Path for the output filtered FASTQ file.
 *   min_quality_filter (Integer): Minimum average base quality for reads to retain.
 *   max_quality_filter (Integer): Maximum average base quality for reads to retain.
 *   minlength (Integer): Minimum read length to retain.
 *   maxlength (Integer): Maximum read length to retain.
 *
 * Output:
 *   ${output} - Filtered FASTQ file.
 *
 * Assumptions:
 *   - samtools and chopper are available in the PATH.
 *   - Input BAM is valid and compatible with samtools bam2fq.
 */
def Bam2FqQualLenFilter(
    reads,
    output,
    min_quality_filter,
    max_quality_filter,
    minlength,
    maxlength
) {
    return """
    samtools bam2fq "${reads}" | chopper \
        --quality "${min_quality_filter}" \
        --maxqual "${max_quality_filter}" \
        --minlength "${minlength}" \
        --maxlength "${maxlength}" > "${output}"
    """.stripIndent().trim()
}

// ======================
// MakeDirectory
// ======================
/*
 * Creates a directory (and any necessary parent directories) at the specified path.
 *
 * Args:
 *   outdir (String): Path of the directory to create.
 *
 * Output:
 *   The specified directory is created if it does not already exist.
 *
 * Assumptions:
 *   - The script has permission to create directories at the specified path.
 *   - mkdir is available in the PATH (standard on all Unix-like systems).
 */
def MakeDirectory(outdir){
    return "mkdir -p ${outdir}"
}

// ======================
// QCReads
// ======================
/*
 * Runs NanoPlot to generate a summary QC report for sequencing reads.
 *
 * Args:
 *   outdir (String): Directory to save the NanoPlot report and outputs.
 *   input_type (String): Specifies the input type flag for NanoPlot (e.g., 'fastq', 'bam').
 *   reads (String): Path to the input read file(s) (FASTQ, BAM, etc.).
 *
 * Output:
 *   The NanoPlot HTML and summary files are generated in the specified output directory.
 *
 * Assumptions:
 *   - NanoPlot is available in the PATH.
 *   - Input reads are compatible with the specified input type.
 */
def QCReads(outdir, input_type, reads){
    return """
    NanoPlot --only-report \
        -o ${outdir} \
        --${input_type} \
        ${reads}
    """.stripIndent().trim()
}

// ======================
// SortBam
// ======================
/*
 * Sorts a BAM file by coordinate using samtools sort, producing a new sorted BAM file.
 *
 * Args:
 *   reads (String): Path to the input BAM file to be sorted.
 *   output (String): Path for the output sorted BAM file.
 *
 * Output:
 *   ${output} - Sorted BAM file.
 *
 * Assumptions:
 *   - Samtools is available in the PATH.
 *   - Input BAM file is valid and unsorted.
 */
def SortBam(reads, output) {
    return "samtools sort -o ${output} ${reads}"
}

// ======================
// AlignWithBowtie2
// ======================
/*
 * Builds a Bowtie2 index for the reference sequence and aligns reads to it,
 * producing a SAM file of alignments. Includes index building as a step
 * for reproducibility and self-contained execution.
 *
 * Args:
 *   reads (String): Path to the input reads file (FASTQ/FASTA).
 *   output (String): Path for the output SAM file containing alignments.
 *   reference (String): Path to the reference FASTA file.
 *   ref_index (String, optional): Prefix for the Bowtie2 index files (default: "ref_index").
 *
 * Output:
 *   ${output} - SAM file with aligned reads.
 *   Bowtie2 index files (with prefix ${ref_index}) are also created in the working directory.
 *
 * Assumptions:
 *   - Bowtie2 is available in the PATH.
 *   - Input reads and reference files are valid and compatible with Bowtie2.
 *   - The working directory is writeable for index and SAM file output.
 */
def AlignWithBowtie2(reads, output, reference, ref_index="ref_index") {
    return """
    set -e
    echo "reads: ${reads}"
    echo "reference: ${reference}"
    ls -lh "${reads}" "${reference}"

    # Build bowtie2 index
    bowtie2-build "${reference}" "${ref_index}"

    # Align reads
    bowtie2 -x "${ref_index}" -U "${reads}" -S "${output}" --very-sensitive-local
    """.stripIndent().trim()
}

// ======================
// AlignWithMinimap2
// ======================
/*
 * Aligns sequencing reads to a reference sequence using minimap2 with specified
 * k-mer size and minimizer window parameters, and outputs the alignments in SAM format.
 *
 * Args:
 *   k (Integer): K-mer size used for seeding.
 *   w (Integer): Minimizer window size.
 *   reference (String): Path to the reference FASTA file.
 *   reads (String): Path to the input reads file (FASTQ, FASTA, etc.).
 *   output (String): Path for the output SAM file containing alignments.
 *
 * Output:
 *   ${output} - SAM file with read alignments to the reference.
 *
 * Assumptions:
 *   - minimap2 is available in the PATH.
 *   - Input reference and reads files are valid and compatible with minimap2.
 */
def AlignWithMinimap2(k, w, reference, reads, output) {
    return """
    minimap2 -k ${k} -w ${w} -ax sr \
    ${reference} ${reads} > ${output}    
    """.stripIndent().trim()
}